version: '2'
services:
  redis:
    image: redis:3
    ports:
      - "6379:6379"
  flume-ng:
    build:
      context: .
      args:
        VERSION: 1.7.0
    command:
      - "conf/redis-list-source.conf"
    volumes:
      - ".:/root"
    links:
      - redis